### ISSUE TITLE
tsc failing for data-browser, cannot find node modules

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-data-browser#237]
For some reason, since last week, `pnpm build` fails on @Polleps machine. It works fine on mine and the CI.

We tried:

- `pnpm purge`
- remove node_modules
- `pnpm install`
- Check versions for pnpm and node

Ultimately, we removed the `tsc` command from the `build` script, since `vite build` can compile typescript files, too. However, this does not do typechecking, so we added the `typecheck` step in the CI.

**Comment by Polleps** [comment]
Also fails in CI

**Comment by joepio** [comment]
> Also fails in CI

Turned out to be a different issue
