### ISSUE TITLE
Theme gets stuck on dark mode when set to auto

### ISSUE THREAD

**Issue by Polleps** [atomicdata-dev/atomic-data-browser#277]
When setting the theme to `auto` it will switch to the `dark` setting when the OS changes to dark mode. It then stays there even if the OS switches back to light mode. When debugging using devtools it works fine so it probably only happens when the system switches to light mode while the app is not running. The theme buttons should also stay selected on the auto option but right now it changes to the respective theme when the system theme changes.

**Comment by joepio** [comment]
Replicated and fixed, thanks!
