### ISSUE TITLE
`getResourceAsync` Race condition returning a still loading resource

### ISSUE THREAD

**Issue by adileo** [atomicdata-dev/atomic-data-browser#309]
While I was working on #75 I needed a way to recursively get the parents of a resource.
I tried to create a new hook backed by recursive calls to `getResourceAsync`.

 I noticed that `getResourceAsync` in `store.ts` suffers from a race condition happening when resource `x` is called by `getResourceLoading(x)` and, while it's still loading, you call `getResourceAsync(x)` it will return a unready resource. 
I suppose this is not the intended behaviour.

Opening a pull request with the fix

**Comment by joepio** [comment]
Fixed by @adileo! Thanks :)
